version: "3.8"

services:
  client:
    container_name: "client"
    image: node:18.16
    entrypoint: ["sh", "./entrypoint.sh"]
    volumes:
      - ./:/usr/text-me/client
      - ./entrypoint.sh:/entrypoint.sh
    env_file:
      - ./.env.production
    networks: 
      - default

  nginx:
    image: nginx:alpine
    depends_on:
      - client
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - "3000:80"
    command: ["nginx", "-g", "daemon off;"]
    networks: 
      - default

networks:
  default: 
    name: text-me
    external: true