version: "3"

services:
  redis:
    container_name: "redis"
    image: redis
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports: 
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks: 
      - default

  postgresql:
    container_name: "postgresql"
    image: bitnami/postgresql
    env_file:
      - ./.env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USERNAME}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    networks:
      - default

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    env_file:
      - ./.env
    ports:
    # AMQP protocol port
    - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
    # HTTP management UI
    - '${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}'
    networks:
      - default

networks:
  default: 
    name: text-me
    external: true