version: "3.8"

services:
  text-me-server:
    container_name: "server"
    image: node:18.16
    entrypoint: ["sh", "./entrypoint.sh"]
    env_file:
      - ./.env.production
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/usr/text-me/server
      - ./entrypoint.sh:/entrypoint.sh
    networks: 
      - default

networks:
  default: 
    name: text-me
    external: true